#!/usr/bin/env python3
"""Claude Code PR Reviewer — structured Markdown review comments."""
import os, sys, subprocess, json
from pathlib import Path

def run(cmd: list[str]) -> str:
    return subprocess.run(cmd, capture_output=True, text=True).stdout.strip()

def get_pr_diff(base: str = "origin/main") -> str:
    try:
        return run(["git", "diff", f"{base}...HEAD"])
    except Exception:
        return run(["git", "diff", "HEAD~1"])

def analyze_diff(diff: str) -> dict:
    findings = {'security': [], 'performance': [], 'style': [], 'logic': [], 'testing': []}
    for line in diff.split('\n'):
        if not line.startswith('+'):
            continue
        if 'console.log' in line:
            findings['security'].append('`console.log` found — use structured logging')
        if 'API_KEY' in line or 'SECRET' in line or 'TOKEN' in line:
            if 'process.env' not in line and 'import' not in line:
                findings['security'].append('Potential secret in code — use env vars')
        if 'as any' in line:
            findings['style'].append('`as any` — use proper typing')
        if 'setTimeout' in line:
            findings['performance'].append('setTimeout — consider alternatives')
        if 'useEffect' in line and 'fetch' in line:
            findings['performance'].append('fetch in useEffect — use Server Components or SWR')
    return findings

def main():
    import argparse
    parser = argparse.ArgumentParser(description='PR Reviewer')
    parser.add_argument('--base', default='origin/main')
    parser.add_argument('--output', default='-')
    args = parser.parse_args()
    
    diff = get_pr_diff(args.base)
    if not diff:
        print("No diff found.")
        sys.exit(1)
    
    changed_files = [l.split()[-1] for l in diff.split('\n') if l.startswith('diff --git')]
    findings = analyze_diff(diff)
    
    lines = [f"## PR Review\n", f"**Files:** {len(changed_files)}\n"]
    for f in changed_files[:20]:
        lines.append(f"- `{f}`")
    
    total = 0
    for cat, items in findings.items():
        if not items:
            continue
        total += len(items)
        emoji = {'security': '🔒', 'performance': '⚡', 'style': '🎨'}
        lines.append(f"\n### {emoji.get(cat,'📌')} {cat.title()}")
        for item in set(items):
            lines.append(f"- {item}")
    
    if total == 0:
        lines.append("\n### ✅ No issues found")
    
    lines.append("\n---\n*Generated by PR Reviewer*")
    output = '\n'.join(lines)
    
    if args.output == '-':
        print(output)
    else:
        with open(args.output, 'w') as f:
            f.write(output)

if __name__ == '__main__':
    main()
